#!/usr/bin/env ruby
# frozen_string_literal: true

ENV_PATH  = File.expand_path('../config/environment', __dir__)
BOOT_PATH = File.expand_path('../config/boot', __dir__)
APP_PATH  = File.expand_path('../config/application', __dir__)

require BOOT_PATH
require 'rails/commands'
